apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.weave.works/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: weave-gitops
      version: "0.38.0"
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
  values:
    adminUser:
      create: true
      username: admin
      # Password is 'admin' (bcrypt hash)
      passwordHash: "$2a$12$Xi4v3s.d4p46ArU0xsjZzuAlLfAo1UD7AAYee0SFoWPuePf1kA93u"
