apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: prometheus
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      hostmetrics:
        root_path: /hostfs
        scrapers:
          cpu:
          memory:
          disk:
          filesystem:
          network:
          load:

    processors:
      batch:
      resourcedetection:
        detectors: [env, system]
        timeout: 2s
        override: false

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
        resource_to_telemetry_conversion:
          enabled: true

    service:
      pipelines:
        metrics:
          receivers: [otlp, hostmetrics]
          processors: [resourcedetection, batch]
          exporters: [prometheus]

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector
  namespace: prometheus
spec:
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      hostPID: true
      hostNetwork: true
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.82.0
          args:
            - "--config=/etc/otel-collector-config.yaml"
          ports:
            - containerPort: 4317 # OTLP gRPC
            - containerPort: 4318 # OTLP HTTP
            - containerPort: 8889 # Prometheus exporter
          volumeMounts:
            - name: otel-collector-config
              mountPath: /etc/otel-collector-config.yaml
              subPath: otel-collector-config.yaml
            - name: hostfs
              mountPath: /hostfs
              readOnly: true
              mountPropagation: HostToContainer
      volumes:
        - name: otel-collector-config
          configMap:
            name: otel-collector-config
        - name: hostfs
          hostPath:
            path: /
